#ruby=ruby@toptal_server
source 'https://rubygems.org'
gem 'rackful', :path => './rackful'
gem 'yaks', :path => './yaks'
#gem 'memcache-client'
#gem 'mechanize'
#gem 'nokogiri', '1.6.1.beta.1'
#gem 'sequel'
